.ds PN flowvisor

.TH flowvisor 8 "May 2008" "FlowVisor" "FlowVisor Manual"

.SH NAME
flowvisor \- OpenFlow network slicing daemon

.SH SYNOPSIS
.B flowvisor
[-d \fIdebug\fR] [-h] [-l] [-p \fIport\fR] \fIconfig.xml\fR 

.SH DESCRIPTION
The
.B flowvisor
program is a daemon that logically slices an OpenFlow-enabled switch into multiple, logical switches each controlled by a different OpenFlow controller. 

For more details, see:

"Can the Production Network Be the Test-bed?" 
Rob Sherwood, Glen Gibb, Kok-Kiong Yap, Guido Appenzeller, Martin Casado, Nick McKeown, Guru Parulkar.
Symposium for Operating Systems Design and Implementation, 2010

.SH OPTIONS

.TP
-d \fIdebug\fR
Overrides debugging threshold in config.xml and sets it to \fIdebug\fR.  Does not modify config.xml.
Mostly used for manual debugging.

.TP
-h
Prints the version number and usage information and exits.


.TP
-l
Logs to stderr instead of to syslog()

.TP
-p \fIport\fR
Overrides listenning port from config.xml and sets it to \fIport\fR.  Does not modify config.xml.
Mostly used for manual debugging.


.SH "SEE ALSO"

.BR fvctl (1)
.BR fvconfig (1)
